language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      
script: mvn install

before_install:
- ./etc/before.sh

deploy:
  skip_cleanup: true
  provider: script
  script: mvn deploy
  on:
    branch: master
